format = """
$character\
"""

right_format = """
$git_branch\
$git_status\
$python\
$lua\
$java\
$c\
$directory\
"""

[directory]
format = "[ $path ](bold #bb9af7)"
truncation_length = 2
truncation_symbol = '…/'

[character]
success_symbol = " [](bold #bb9af7)"
error_symbol = " [✖](bold #f7768e)"

[git_branch]
format = '[$symbol $branch]($style) via '

[git_status]
format = '[$all_status$ahead_behind ]($style) '

[python]
format = '  via '

[lua]
format = '󰢱  via '

[java]
format = '  via '

[c]
format = '  via '
